repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Linter
        language: system
        types: [python]
        entry: uv run ruff check --fix src
        require_serial: true
        stages: [pre-commit, pre-push, manual]

      - id: ruff-format
        name: Ruff Formatter
        language: system
        types: [python]
        entry: uv run ruff format src
        require_serial: true
        stages: [pre-commit, pre-push, manual]

      - id: mypy
        name: mypy
        entry: uv run mypy src
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false

      - id: ty
        name: ty
        entry: uv run ty src
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
