version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - export UV_LINK_MODE=copy uv run python -m sphinx docs $READTHEDOCS_OUTPUT/html -b html

sphinx:
  configuration: docs/conf.py