[project]
name = "auntie-sounds"
version = "1.0.0"
description = "A library for interacting with BBC Radio stations and streams"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohappyeyeballs>=2.6.1",
    "aiohttp>=3.12.13",
    "aiosignal>=1.4.0",
    "attrs>=25.3.0",
    "beautifulsoup4>=4.13.4",
    "colorlog>=6.9.0",
    "frozenlist>=1.7.0",
    "idna>=3.10",
    "multidict>=6.6.3",
    "propcache>=0.3.2",
    "soupsieve>=2.7",
    "typing-extensions>=4.14.1",
    "yarl>=1.20.1",
]

[build-system]
requires = ["uv_build>=0.7.19,<0.8"]
build-backend = "uv_build"

[tool.uv.build-backend]
package-dir = "src"
namespace = true
module-name = "sounds"

