name: Upload Python Package (to PyPi test)
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'pypi-test'
jobs:
  pypi-publish:
    name: Upload release to PyPI Test
    runs-on: ubuntu-latest
    environment:
      name: pypi-test
      url: https://test.pypi.org/p/auntie-sounds
    permissions:
      id-token: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
